contact_links:
  - name: Feature Request
    about: Request a new feature
    url: https://github.com/mchelen-gov/project-automation-test/issues/new?template=FEATURE_REQUEST.md&projects=project-automation-test%2Fproject_a%2F1
